### PR TITLE
Building with Active Record

### PR DESCRIPTION
**Pull request by emmanuellekamwa**
In this project, I have made use of the following:
- Used active record as said in the odin project
- Use rubocop for testing

### CODE REVIEW

**Review by cristianCeamatu — CHANGES_REQUESTED** [review]
## ♻️ Changes required
#### Congratulations for your efforts! The logic was easy to follow and understand and your project works! You also found a very nice way to improve the UI by going the extra mile and add a voting system. 👏 👏 👏 
However, there are some small changes to be done in order to get this project approved:

- [ ] Please fix the stylelint linter errors on your PR
- [ ] Add `node_modules` folder to `.gitignore`
- [ ] A comment can be created ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingComment.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)) I can create comments from the console but from the website is not workings, probably you have an error in the controller. Screenshot of the error:
Error

##### User
- [ ] username is validated (at least for the presence) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/userValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)). I can create an account without even adding a name in the form, this should not be possible.
- [ ] `has_many :comments` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_comments.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails)). Your user should have the many comments relations, comments cannot exist without being created by the user.

##### Links
- [ ] validations are present ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/postValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

##### Comment
- [ ] validations are present ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/commentValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

Don't hesitate to contact me on Slack if needed, I would be happy to join your call and help.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Comment by emmanuellekamwa** [comment]
In this project, I have made use of the following:
- Fixed the stylelint and rubocop errors
- Fixed everything the TSE told me to fix

**Review by LamiaSristy — CHANGES_REQUESTED** [review]
# Status: Change Required. ♻️

Hello @emmanuellekamwa  🙌

Great work so far.

You need to implement the works below to get the project approved!🛠️

Please check my points here: 👇

`[REQUIRED]`

 - [ ] In README.md file add instructions for how to clone and set-up/run your project locally. you can use [this](https://github.com/microverseinc/readme-template) template.
 
 - [ ] In your `.gitignore` file, write `\node_module` with a `\` sign. 
 
 - [ ] In `User.rb`, add `has_many :posts` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/user_has_many_posts.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

 - [ ] In `Comment.rb` add `belongs_to :post` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/comment_belongs_to_a_post.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
 

Please make the changes and ask for a re-review.

Feel free to reach me at @lamiasristy 🙋

**Comment by emmanuellekamwa** [comment]
I have resolved all the issues pointed out by the TSE

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔**
Hello team,
Great work implementing the required changes👏
You can merge

**Pull request merged**
